# Generated by Django 6.0.3 on 2026-03-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('genero', models.CharField(choices=[('Ficção', 'Ficção'), ('Não Ficção', 'Não Ficção'), ('Tecnologia', 'Tecnologia'), ('Ciência', 'Ciência'), ('História', 'História')], max_length=50)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Emprestado', 'Emprestado'), ('Lido', 'Lido')], default='Disponível', max_length=20)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
